### ISSUE TITLE
Install issues with Conan 

### ISSUE THREAD

**Issue by mattrenderedai** [petrikvladimir/pyphysx#74]
I am getting a error with conan when attempting to install pyphysx. I am using a fresh environment - a container based on nvidia/cuda:12.0.1-base-ubuntu20.04 with Python 3.8 and cmake. 
- cmake 3.16.1
- python 3.8.16
- conan 2.0.4.

The error:
`conan remote: error: unrecognized arguments: True`

**Is this an issue with my configuration, e.g. of conan, or with your build scripts?**

Full log attached, here is the part with the error
```
Building wheels for collected packages: pyphysx
  Building wheel for pyphysx (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [91 lines of output]
      /home/anadev/miniconda3/envs/anatools/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/pyphysx_render
      copying pyphysx_render/utils.py -> build/lib.linux-x86_64-cpython-38/pyphysx_render
      copying pyphysx_render/pyrender_base.py -> build/lib.linux-x86_64-cpython-38/pyphysx_render
      copying pyphysx_render/pyrender.py -> build/lib.linux-x86_64-cpython-38/pyphysx_render
      copying pyphysx_render/pyrender_offscreen_renderer.py -> build/lib.linux-x86_64-cpython-38/pyphysx_render
      copying pyphysx_render/meshcat_render.py -> build/lib.linux-x86_64-cpython-38/pyphysx_render
      copying pyphysx_render/render_base.py -> build/lib.linux-x86_64-cpython-38/pyphysx_render
      copying pyphysx_render/pyrender_trackball.py -> build/lib.linux-x86_64-cpython-38/pyphysx_render
      copying pyphysx_render/__init__.py -> build/lib.linux-x86_64-cpython-38/pyphysx_render
      creating build/lib.linux-x86_64-cpython-38/pyphysx_utils
      copying pyphysx_utils/transformations.py -> build/lib.linux-x86_64-cpython-38/pyphysx_utils
      copying pyphysx_utils/rate.py -> build/lib.linux-x86_64-cpython-38/pyphysx_utils
      copying pyphysx_utils/tree_robot.py -> build/lib.linux-x86_64-cpython-38/pyphysx_utils
      copying pyphysx_utils/__init__.py -> build/lib.linux-x86_64-cpython-38/pyphysx_utils
      copying pyphysx_utils/urdf_robot_parser.py -> build/lib.linux-x86_64-cpython-38/pyphysx_utils
      running build_ext
      -- The C compiler identification is GNU 9.4.0
      -- The CXX compiler identification is GNU 9.4.0
      -- Check for working C compiler: /usr/bin/cc
      -- Check for working C compiler: /usr/bin/cc -- works
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Check for working CXX compiler: /usr/bin/c++
      -- Check for working CXX compiler: /usr/bin/c++ -- works
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Conan: Adding conan-center remote repository (https://center.conan.io) verify ssl (True)
      usage: conan remote [-h] [-v [V]]
                          {add,auth,disable,enable,list,list-users,login,logout,remove,rename,set-user,update}
                          ...
      conan remote: error: unrecognized arguments: True
      ERROR: Exiting with code: 2
      CMake Error at build/temp.linux-x86_64-cpython-38/conan.cmake:974 (message):
        Conan remote failed='2'
      Call Stack (most recent call first):
        CMakeLists.txt:13 (conan_add_remote)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-req-build-tb887eja/build/temp.linux-x86_64-cpython-38/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-tb887eja/setup.py", line 68, in <module>
          setup(
        File "/home/anadev/miniconda3/envs/anatools/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/anadev/miniconda3/envs/anatools/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/anadev/miniconda3/envs/anatools/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/anadev/miniconda3/envs/anatools/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/anadev/miniconda3/envs/anatools/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/anadev/miniconda3/envs/anatools/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/anadev/miniconda3/envs/anatools/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/home/anadev/miniconda3/envs/anatools/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/anadev/miniconda3/envs/anatools/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/anadev/miniconda3/envs/anatools/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/anadev/miniconda3/envs/anatools/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/anadev/miniconda3/envs/anatools/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/anadev/miniconda3/envs/anatools/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/anadev/miniconda3/envs/anatools/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-req-build-tb887eja/setup.py", line 32, in run
          self.build_extension(ext)
        File "/tmp/pip-req-build-tb887eja/setup.py", line 64, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
        File "/home/anadev/miniconda3/envs/anatools/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-tb887eja', '-DPHYSX_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-tb887eja/build/lib.linux-x86_64-cpython-38/', '-DPYTHON_EXECUTABLE=/home/anadev/miniconda3/envs/anatools/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
   
[pyphysx-pi-install.log](https://github.com/petrikvladimir/pyphysx/files/11499893/pyphysx-pi-install.log)
   [end of output]
```

**Comment by mattrenderedai** [comment]
@petrikvladimir does this look correct?
```
$ conan remote list
conancenter: https://center.conan.io [Verify SSL: True, Enabled: True]
```

**Comment by petrikvladimir** [comment]
Hi, I am aware of the not working installation in conda, I was trying to fix it here https://github.com/petrikvladimir/pyphysx/pull/73, but without success so far. I will find some time next week to resolve it.

**Comment by mattrenderedai** [comment]
@petrikvladimir , the conda-install branch seems to work for me. I can run `pip install git+https://github.com/petrikvladimir/pyphysx.git@conda_installation` without issue.

Now I am trying to run your trivial example and getting an error from the version of Pillow (I have 9.4.0)

scripts$ python physx_example.py 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/rob1nson/anaconda3/envs/pyphysx/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/rob1nson/anaconda3/envs/pyphysx/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rob1nson/anaconda3/envs/pyphysx/lib/python3.8/site-packages/pyrender/viewer.py", line 1030, in _init_and_start_app
    pyglet.app.run()
  File "/home/rob1nson/anaconda3/envs/pyphysx/lib/python3.8/site-packages/pyglet/app/__init__.py", line 76, in run
    event_loop.run(interval)
  File "/home/rob1nson/anaconda3/envs/pyphysx/lib/python3.8/site-packages/pyglet/app/base.py", line 151, in run
    timeout = self.idle()
  File "/home/rob1nson/anaconda3/envs/pyphysx/lib/python3.8/site-packages/pyglet/app/base.py", line 212, in idle
    self.clock.call_scheduled_functions(dt)
  File "/home/rob1nson/anaconda3/envs/pyphysx/lib/python3.8/site-packages/pyglet/clock.py", line 227, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/home/rob1nson/anaconda3/envs/pyphysx/lib/python3.8/site-packages/pyrender/viewer.py", line 879, in _time_event
    self.on_draw()
  File "/home/rob1nson/anaconda3/envs/pyphysx/lib/python3.8/site-packages/pyphysx_render/pyrender.py", line 139, in on_draw
    self.video_writer.append_data(data)
  File "/home/rob1nson/anaconda3/envs/pyphysx/lib/python3.8/site-packages/imageio/v2.py", line 215, in append_data
    return self.instance.write(im, **self.write_args)
  File "/home/rob1nson/anaconda3/envs/pyphysx/lib/python3.8/site-packages/imageio/plugins/pillow.py", line 354, in write
    raise TypeError(
TypeError: The keyword `fps` is no longer supported. Use `duration`(in ms) instead, e.g. `fps=50` == `duration=20` (1000 * 1/50).

**Comment by petrikvladimir** [comment]
Thank you for reporting. I fixed it in the conda-installation branch. However, I still need to resolve the Windows installation before merging into the main.

**Comment by mattrenderedai** [comment]
Thank you @petrikvladimir you can close this - I have successfully run your Off Screen example in our application docker.
